### ISSUE TITLE
Incorrect username and/or password

### ISSUE THREAD

**Issue by a2** [KrauseFx/fasttrack#1]
`refresher.fastlane.tools` seems to reject the username and password combination `admin:removed`. Please advise?

**Comment by neonichu** [comment]
@KrauseFx !!!!!

![](https://media.giphy.com/media/M11UVCRrc0LUk/giphy.gif)

**Comment by KrauseFx** [comment]
![http://i.giphy.com/zyclIRxMwlY40.gif](http://i.giphy.com/zyclIRxMwlY40.gif)

**Comment by garfbargle** [comment]
@a2 the password is 'removed', seems like a very good indication that it's purposeful.

**Comment by KrauseFx** [comment]
@garfbargle :sparkles:

**Comment by KrauseFx** [comment]
This is fixed now :+1:
