### ISSUE TITLE
Page hotlinks easing script

### ISSUE THREAD

**Issue by a2** [KrauseFx/fasttrack#2]
![screen shot 2016-03-22 at 5 56 08 pm](https://cloud.githubusercontent.com/assets/241156/13960154/729bcdb8-f057-11e5-8f27-97237f19dd7d.png)

**Comment by KrauseFx** [comment]
Haha, I haven't seen that message, but I should do that :+1:

**Comment by KrauseFx** [comment]
Fixed with https://github.com/KrauseFx/fasttrack/commit/99535580455091ce45758a704d0ed7754f4dc638
